SELECT
	ACTOR.ACTOR_ID,
	ACTOR.FIRST_NAME,
	ACTOR.LAST_NAME,
	COUNT(RENTAL.RENTAL_ID) AS COUNT_RENTAL
FROM
	ACTOR
	JOIN FILM_ACTOR ON ACTOR.ACTOR_ID = FILM_ACTOR.ACTOR_ID
	JOIN FILM ON FILM_ACTOR.FILM_ID = FILM.FILM_ID
	JOIN INVENTORY ON FILM.FILM_ID = INVENTORY.FILM_ID
	JOIN RENTAL ON INVENTORY.INVENTORY_ID = RENTAL.INVENTORY_ID
GROUP BY
	ACTOR.ACTOR_ID
ORDER BY
	COUNT_RENTAL DESC
LIMIT
	10