-- 1. Number of movies in each category, sorted descending
SELECT
	CATEGORY.NAME,
	COUNT(FILM.FILM_ID) AS FILM_COUNT
FROM
	FILM
	JOIN FILM_CATEGORY ON FILM.FILM_ID = FILM_CATEGORY.FILM_ID
	JOIN CATEGORY ON CATEGORY.CATEGORY_ID = FILM_CATEGORY.CATEGORY_ID
GROUP BY
	CATEGORY.NAME
ORDER BY
	2 DESC
	