SELECT
	CITY.CITY_ID,
	CITY.CITY,
	COUNT(
		CASE
			WHEN CUSTOMER.ACTIVE = 1 THEN 1
		END
	) AS ACTIVE_CUSTOMERS,
	COUNT(
		CASE
			WHEN CUSTOMER.ACTIVE = 0 THEN 1
		END
	) AS INACTIVE_CUSTOMERS
FROM
	CITY
	JOIN ADDRESS ON CITY.CITY_ID = ADDRESS.CITY_ID
	JOIN CUSTOMER ON ADDRESS.ADDRESS_ID = CUSTOMER.ADDRESS_ID
GROUP BY
	CITY.CITY_ID,
	CITY.CITY
ORDER BY
	INACTIVE_CUSTOMERS DESC