-- 3. Output the category of movies on which the most money was spent.

SELECT
	CATEGORY.CATEGORY_ID,
	CATEGORY.NAME,
	SUM(PAYMENT.AMOUNT) AS CATEGORY_REVENUE
FROM
	FILM_CATEGORY 
	JOIN CATEGORY ON FILM_CATEGORY.CATEGORY_ID = CATEGORY.CATEGORY_ID
	JOIN INVENTORY ON FILM_CATEGORY.FILM_ID = INVENTORY.FILM_ID
	JOIN RENTAL ON INVENTORY.INVENTORY_ID = RENTAL.INVENTORY_ID
	JOIN PAYMENT ON RENTAL.RENTAL_ID = PAYMENT.RENTAL_ID
GROUP BY
	CATEGORY.CATEGORY_ID,
	CATEGORY.NAME
ORDER BY
	CATEGORY_REVENUE DESC
LIMIT
	1;