-- 7. Output the category of movies that have the highest number of total rental hours in the city (customer.address_id in this city) and that start with the letter “a”. Do the same for cities that have a “-” in them. Write everything in one query.

WITH
	RENTAL_HOURS AS (
		SELECT
			CITY.CITY AS CITY,
			CATEGORY.NAME AS CATEGORY_NAME,
			SUM(
				EXTRACT(
					EPOCH
					FROM
						COALESCE(RENTAL.RETURN_DATE, NOW()) - RENTAL.RENTAL_DATE
				) / 3600
			) AS TOTAL_RENTAL_HOURS
		FROM
			RENTAL
			JOIN CUSTOMER ON RENTAL.CUSTOMER_ID = CUSTOMER.CUSTOMER_ID
			JOIN ADDRESS ON CUSTOMER.ADDRESS_ID = ADDRESS.ADDRESS_ID
			JOIN CITY ON ADDRESS.CITY_ID = CITY.CITY_ID
			JOIN INVENTORY ON RENTAL.INVENTORY_ID = INVENTORY.INVENTORY_ID
			JOIN FILM ON INVENTORY.FILM_ID = FILM.FILM_ID
			JOIN FILM_CATEGORY ON FILM.FILM_ID = FILM_CATEGORY.FILM_ID
			JOIN CATEGORY ON FILM_CATEGORY.CATEGORY_ID = CATEGORY.CATEGORY_ID
		WHERE
			CITY.CITY ILIKE 'a%'
			OR CITY.CITY LIKE '%-%'
		GROUP BY
			CITY.CITY,
			CATEGORY.NAME
	),
	RANKED AS (
		SELECT
			CITY,
			CATEGORY_NAME,
			TOTAL_RENTAL_HOURS,
			RANK() OVER (
				PARTITION BY
					CITY
				ORDER BY
					TOTAL_RENTAL_HOURS DESC
			) AS RNK
		FROM
			RENTAL_HOURS
	)
SELECT
	CITY,
	CATEGORY_NAME,
	TOTAL_RENTAL_HOURS,
	RNK
FROM
	RANKED
WHERE
	RNK = 1